name: researcher

x-app: &app
  environment:
    - BRAVE_API_KEY=${BRAVE_API_KEY:-}
    - DEFAULT_MODEL_NAME=${DEFAULT_MODEL_NAME:-}
    - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    - JINA_API_KEY=${JINA_API_KEY:-}
    - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    - SERPER_API_KEY=${SERPER_API_KEY:-}
  secrets:
    - npm_token
  depends_on:
    researcher-cache-pnpm:
      condition: service_completed_successfully
  networks:
    - host
    - local
  ports:
    - "3000:3000"

services:
  researcher-cache-pnpm:
    image: ghcr.io/piktur/finance/devcontainers/base:debian
    platform: linux/arm64
    user: root
    working_dir: /app
    environment:
      PNPM_HOME: /app/.pnpm-store
    secrets:
      - npm_token
    volumes:
      - .:/app
      - researcher_node_modules:/app/node_modules
      - npm:/root/.npm
      - $PNPM_HOME/store/v3:/app/.pnpm-store
      - pnpm:/app/.pnpm-store
    command: /app/bin/pnpm/setup.sh

  researcher-dev:
    <<: *app
    image: node:22.14.0-slim
    user: node
    working_dir: /app/packages/node-deepresearch
    volumes:
      - .:/app
      - researcher_node_modules:/app/node_modules

  researcher-www:
    <<: *app
    image: node:22.14.0-slim
    user: node
    working_dir: /app/packages/node-deepresearch
    volumes:
      - .:/app
      - researcher_node_modules:/app/node_modules
    entrypoint: "node"
    command: ["./dist/server.js"]
    healthcheck:
      test: ['CMD-SHELL', 'curl -fI http://0.0.0.0:3000/health']
      interval: 5s
      timeout: 5s
      retries: 3

  researcher-production:
    <<: *app
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - npm_token

networks:
  host:
  local:
    external: true

volumes:
  researcher_node_modules:
