name: researcher

x-app: &app
  environment:
    NPM_TOKEN: ${NPM_TOKEN:-}
    BRAVE_API_KEY: ${BRAVE_API_KEY:-}
    DEFAULT_MODEL_NAME: ${DEFAULT_MODEL_NAME:-}
    GEMINI_API_KEY: ${GEMINI_API_KEY:-}
    JINA_API_KEY: ${JINA_API_KEY:-}
    OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    SERPER_API_KEY: ${SERPER_API_KEY:-}
  secrets:
    - npm_token
  depends_on:
    researcher-cache-pnpm:
      condition: service_completed_successfully
  networks:
    - host
    - local

services:
  researcher-cache-pnpm:
    image: ghcr.io/piktur/finance/devcontainers/base:debian
    user: root
    profiles:
      - devcontainer
      - development
      - init
    working_dir: /app
    environment:
      PNPM_HOME: /app/.pnpm-store
    secrets:
      - npm_token
    volumes:
      - ${HOST_HOME}/Code/piktur/node-DeepResearch:/app
      - researcher_node_modules:/app/node_modules
      - npm:/root/.npm
      - ${PNPM_HOME}/store/v3:/app/.pnpm-store
      - pnpm:/app/.pnpm-store
    command: ["./bin/pnpm/setup.sh"]

  researcher-dev:
    <<: *app
    image: node:22.14.0-slim
    user: node
    profiles:
      - devcontainer
      - development
    working_dir: /app/packages/node-deepresearch
    volumes:
      - ${HOST_HOME}/Code/piktur/node-DeepResearch:/app
      - researcher_node_modules:/app/node_modules
    entrypoint: "node"

  researcher-www:
    <<: *app
    image: node:22.14.0-slim
    user: node
    profiles:
      - devcontainer
      - development
    working_dir: /app/packages/node-deepresearch
    ports:
      - "3017:3000"
    volumes:
      - ${HOST_HOME}/Code/piktur/node-DeepResearch:/app
      - researcher_node_modules:/app/node_modules
    entrypoint: "node"
    command: ["./dist/server.js"]
    healthcheck:
      test: [
        'CMD-SHELL',
        "node -e 'fetch(\"http://localhost:3000/health\").then(res => process.exit(res.ok ? 0 : 1))'"
      ]
      interval: 10s
      timeout: 10s
      retries: 3

networks:
  host:
  local:
    external: true

volumes:
  researcher_node_modules:

secrets:
  npm_token:
    environment: NPM_TOKEN
